# -*- coding: utf-8 -*-
"""Pregunta 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U3OzUKb9PFa9DF0rJznGVi0Uvs29jkQQ
"""

def usuario():
    nombre = input("Por favor ingrese su nombre: ")
    print(f"Hola, {nombre}! Encantado de conocerte.")
    print()
    print(f"¿En qué te puedo ayudar, {nombre}?")

usuario()